/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_knock_100_jni_Java19 */

#ifndef _Included_java_knock_100_jni_Java19
#define _Included_java_knock_100_jni_Java19
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_knock_100_jni_Java19
 * Method:    stringFromJNI
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_java_1knock_1100_jni_Java19_stringFromJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
